from helpers.exception import CycleError